version: '3.1'

services:
  db:
    image: postgres:13.3
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django

  pgadmin:
    image: dpage/pgadmin4:5.4
    container_name: pgadmin
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    depends_on:
      - db
